"""initial tables

Revision ID: 60801e59976b
Revises: 
Create Date: 2026-02-07 12:02:11.471831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60801e59976b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='能力名称'),
    sa.Column('code', sa.String(length=30), nullable=False, comment='能力编码，如 detail_extraction'),
    sa.Column('category', sa.Enum('INFORMATION', 'COMPREHENSION', 'ANALYSIS', 'EXPRESSION', name='abilitycategoryenum'), nullable=False, comment='能力分类'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='能力描述'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ability_dimensions_id'), 'ability_dimensions', ['id'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='文章内容'),
    sa.Column('source_book', sa.String(length=200), nullable=True, comment='来源书籍，如《伊索寓言》'),
    sa.Column('source_chapter', sa.String(length=200), nullable=True, comment='来源章节'),
    sa.Column('is_excerpt', sa.Boolean(), nullable=True, comment='是否为节选'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='字数'),
    sa.Column('reading_time', sa.Integer(), nullable=False, comment='预计阅读时间(分钟)'),
    sa.Column('article_difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultyenum'), nullable=True, comment='文章难度'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'PUBLISHED', 'ARCHIVED', name='articlestatusenum'), nullable=True, comment='状态'),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True, comment='是否AI导入'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID（管理员）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='勋章名称'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='勋章描述'),
    sa.Column('icon_url', sa.String(length=512), nullable=True, comment='勋章图标URL'),
    sa.Column('category', sa.Enum('PERSISTENCE', 'ABILITY', 'READING', 'EXPLORE', name='badgecategoryenum'), nullable=False, comment='勋章分类'),
    sa.Column('condition_type', sa.Enum('FIRST_READING', 'STREAK_DAYS', 'TOTAL_READINGS', 'ABILITY_ACCURACY', 'ABILITY_COUNT', 'GENRE_COUNT', 'ALL_GENRES', name='badgeconditiontypeenum'), nullable=False, comment='条件类型'),
    sa.Column('condition_value', sa.Integer(), nullable=False, comment='条件阈值'),
    sa.Column('condition_extra', sa.String(length=100), nullable=True, comment='额外条件参数'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名称'),
    sa.Column('category', sa.Enum('GRADE', 'GENRE', 'SOURCE', 'THEME', 'CULTURE', 'ADAPTATION', name='tagcategoryenum'), nullable=False, comment='标签分类'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='标签描述'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='显示顺序'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'category', name='uq_tag_name_category')
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False, comment='微信OpenID'),
    sa.Column('nickname', sa.String(length=64), nullable=True, comment='昵称'),
    sa.Column('avatar_url', sa.String(length=512), nullable=True, comment='头像URL'),
    sa.Column('grade', sa.Enum('GRADE_1', 'GRADE_2', 'GRADE_3', 'GRADE_4', 'GRADE_5', 'GRADE_6', name='gradeenum'), nullable=True, comment='年级'),
    sa.Column('total_readings', sa.Integer(), nullable=True, comment='累计阅读篇数'),
    sa.Column('streak_days', sa.Integer(), nullable=True, comment='当前连续打卡天数'),
    sa.Column('max_streak_days', sa.Integer(), nullable=True, comment='最长连续打卡天数'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'tag_id', name='uq_article_tag')
    )
    op.create_index(op.f('ix_article_tags_article_id'), 'article_tags', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_tags_id'), 'article_tags', ['id'], unique=False)
    op.create_index(op.f('ix_article_tags_tag_id'), 'article_tags', ['tag_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CHOICE', 'JUDGE', 'FILL', 'SHORT_ANSWER', name='questiontypeenum'), nullable=False, comment='题目类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='题干内容'),
    sa.Column('options', sa.JSON(), nullable=True, comment='选项（选择题）'),
    sa.Column('answer', sa.Text(), nullable=False, comment='正确答案'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='答案解析'),
    sa.Column('hint', sa.String(length=500), nullable=True, comment='温柔提示'),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficultyenum'), nullable=True, comment='题目难度'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='题目顺序'),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True, comment='是否AI生成'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_article_id'), 'questions', ['article_id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('user_abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True, comment='正确题数'),
    sa.Column('total_count', sa.Integer(), nullable=True, comment='总题数'),
    sa.Column('score', sa.Float(), nullable=True, comment='能力得分（0-100）'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['ability_id'], ['ability_dimensions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ability_id', name='uq_user_ability')
    )
    op.create_index(op.f('ix_user_abilities_ability_id'), 'user_abilities', ['ability_id'], unique=False)
    op.create_index(op.f('ix_user_abilities_id'), 'user_abilities', ['id'], unique=False)
    op.create_index(op.f('ix_user_abilities_user_id'), 'user_abilities', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True, comment='获得时间'),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_id', name='uq_user_badge')
    )
    op.create_index(op.f('ix_user_badges_badge_id'), 'user_badges', ['badge_id'], unique=False)
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_progresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True, comment='得分（百分制）'),
    sa.Column('correct_count', sa.Integer(), nullable=True, comment='正确题数'),
    sa.Column('total_count', sa.Integer(), nullable=True, comment='总题数'),
    sa.Column('time_spent', sa.Integer(), nullable=True, comment='用时（秒）'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progresses_article_id'), 'user_progresses', ['article_id'], unique=False)
    op.create_index(op.f('ix_user_progresses_id'), 'user_progresses', ['id'], unique=False)
    op.create_index(op.f('ix_user_progresses_user_id'), 'user_progresses', ['user_id'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False, comment='打卡日期'),
    sa.Column('progress_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='打卡时间'),
    sa.ForeignKeyConstraint(['progress_id'], ['user_progresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'check_date', name='uq_user_check_date')
    )
    op.create_index(op.f('ix_check_ins_check_date'), 'check_ins', ['check_date'], unique=False)
    op.create_index(op.f('ix_check_ins_id'), 'check_ins', ['id'], unique=False)
    op.create_index(op.f('ix_check_ins_user_id'), 'check_ins', ['user_id'], unique=False)
    op.create_table('question_abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True, comment='权重 1-10'),
    sa.ForeignKeyConstraint(['ability_id'], ['ability_dimensions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'ability_id', name='uq_question_ability')
    )
    op.create_index(op.f('ix_question_abilities_ability_id'), 'question_abilities', ['ability_id'], unique=False)
    op.create_index(op.f('ix_question_abilities_id'), 'question_abilities', ['id'], unique=False)
    op.create_index(op.f('ix_question_abilities_question_id'), 'question_abilities', ['question_id'], unique=False)
    op.create_table('question_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True, comment='用户答案'),
    sa.Column('is_correct', sa.Boolean(), nullable=True, comment='是否正确'),
    sa.Column('ai_score', sa.Integer(), nullable=True, comment='AI评分（0-100）'),
    sa.Column('ai_feedback', sa.Text(), nullable=True, comment='AI反馈'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='答题时间'),
    sa.ForeignKeyConstraint(['progress_id'], ['user_progresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_answers_id'), 'question_answers', ['id'], unique=False)
    op.create_index(op.f('ix_question_answers_progress_id'), 'question_answers', ['progress_id'], unique=False)
    op.create_index(op.f('ix_question_answers_question_id'), 'question_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_answers_question_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_progress_id'), table_name='question_answers')
    op.drop_index(op.f('ix_question_answers_id'), table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index(op.f('ix_question_abilities_question_id'), table_name='question_abilities')
    op.drop_index(op.f('ix_question_abilities_id'), table_name='question_abilities')
    op.drop_index(op.f('ix_question_abilities_ability_id'), table_name='question_abilities')
    op.drop_table('question_abilities')
    op.drop_index(op.f('ix_check_ins_user_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_check_date'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_user_progresses_user_id'), table_name='user_progresses')
    op.drop_index(op.f('ix_user_progresses_id'), table_name='user_progresses')
    op.drop_index(op.f('ix_user_progresses_article_id'), table_name='user_progresses')
    op.drop_table('user_progresses')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_user_abilities_user_id'), table_name='user_abilities')
    op.drop_index(op.f('ix_user_abilities_id'), table_name='user_abilities')
    op.drop_index(op.f('ix_user_abilities_ability_id'), table_name='user_abilities')
    op.drop_table('user_abilities')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_article_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_article_tags_tag_id'), table_name='article_tags')
    op.drop_index(op.f('ix_article_tags_id'), table_name='article_tags')
    op.drop_index(op.f('ix_article_tags_article_id'), table_name='article_tags')
    op.drop_table('article_tags')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_ability_dimensions_id'), table_name='ability_dimensions')
    op.drop_table('ability_dimensions')
    # ### end Alembic commands ###
